# This work flow will create a tag when merging to main

name: Tag on merge

on:
  pull_request_target:
    types:
      - closed
    branches: [ main ]
    
env:
  VERSION_FILE: version.properties
  VERSION_EXTRACT_PATTERN: '(?<=VERSION_NUMBER=).+'
  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_EXTRACT_PATTERN }}
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ env.CURRENT_VERSION }}"
          message: "Latest release"
    
