# This work flow will create a tag when merging to stage
name: Notify Slack

on: 
  release:
  
    
env:
  VERSION_FILE: version.properties
  VERSION_EXTRACT_PATTERN: '(?<=VERSION_NUMBER=).+'
  
jobs:
  Tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Get Spacejam version
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_EXTRACT_PATTERN }}
      - name: Tagging release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.CURRENT_VERSION }}"
